# Generated by Django 3.2 on 2022-11-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221129_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_time',
        ),
    ]
